version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.5
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          exclude: RC007
          filters: *filters
      - shellcheck/check:
          exclude: SC2034 SC2086
          filters: *filters
      - orb-tools/publish:
          orb-name: roost/roost-orb-test-1
          vcs-type: << pipeline.project.type >>
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          # Use a context to hold your publishing token.
          context: orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters

# VS Code Extension Version: 1.5.1